FROM node:12.13-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install -g npm && \
    npm install --production

ENV NODE_ENV=production

COPY . ./
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
